# Generated by Django 4.1 on 2022-12-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriresto',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
