# Generated by Django 4.1 on 2022-12-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger5', '0002_alter_kategoriresto_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategoriresto',
            old_name='title',
            new_name='kategori',
        ),
    ]
